/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.EnderecoController;
import Controllers.UsuarioController;
import Models.EnderecoModel;
import Models.UsuarioModel;
import Support.CEPFormattedTextField;
import Support.CPFFormattedTextField;
import Support.DataNascimentoFormattedTextField;
import static Support.DataNascimentoFormattedTextField.DateFormatExample;
import Support.InvalidKeyException;
import Support.KeyViolationException;
import Support.NotFoundException;
import Support.NumerosTextField;
import static Support.ValidacaoDataNascimento.validarDataNascimento;
import Support.ViaCEP;
import static Support.ValidacaoCPF.validarCPF;
import TablesModel.UsuariosTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class CadastroUsuarioView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuarioView
     */
    private int id = 0;

    public CadastroUsuarioView() {
        initComponents();
        this.carregarUsuarios("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupUsuario = new javax.swing.ButtonGroup();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new DataNascimentoFormattedTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelCargo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new CPFFormattedTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanelEndereco = new javax.swing.JPanel();
        jLabelCep = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new NumerosTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jFormattedTextFieldCep = new CEPFormattedTextField();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelBusca = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jPanelTipoDeCadastro = new javax.swing.JPanel();
        jRadioButtonCliente = new javax.swing.JRadioButton();
        jRadioButtonFuncionario = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FlicksNPlay - Cadastro De Usuários");
        setResizable(false);

        jPanelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabelDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDataNascimento.setText("Nascimento:");

        jFormattedTextFieldDataNascimento.setPreferredSize(new java.awt.Dimension(180, 22));

        jLabelSenha.setVisible(false);
        jLabelSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");

        jPasswordFieldSenha.setVisible(false);

        jLabelCargo.setVisible(false);
        jLabelCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCargo.setText("Cargo:");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jComboBoxCargo.setVisible(false);
        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCargo.removeAllItems();
        jComboBoxCargo.addItem("");
        jComboBoxCargo.addItem("Gerente");
        jComboBoxCargo.addItem("Balconista");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmail.setText("E-mail:");

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCpf.setText("CPF:");

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldCpf)
                    .addComponent(jTextFieldNome)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataNascimento)
                    .addComponent(jLabelSenha)
                    .addComponent(jLabelCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordFieldSenha)
                    .addComponent(jComboBoxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNascimento)
                    .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelSenha)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCargo)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabelCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCep.setText("CEP:");

        jLabelRua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRua.setText("Rua:");

        jLabelNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNumero.setText("Número:");

        jLabelBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBairro.setText("Bairro:");

        jLabelCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCidade.setText("Cidade:");

        jTextFieldCidade.setEditable(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldCidade.setRequestFocusEnabled(false);

        jLabelEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEstado.setText("Estado:");

        jTextFieldEstado.setEditable(false);
        jTextFieldEstado.setEnabled(false);
        jTextFieldEstado.setRequestFocusEnabled(false);

        jFormattedTextFieldCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCepKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCep)
                    .addComponent(jLabelRua)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNumero)
                    .addComponent(jTextFieldRua)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEstado)
                            .addComponent(jLabelBairro))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelCidade)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCidade)))
                .addContainerGap())
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBairro)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCidade)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCep)
                            .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumero)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPaneUsuarios.setViewportView(jTableUsuarios);

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.setEnabled(false);
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelBusca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBusca.setText("Buscar:");

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jPanelTipoDeCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroupUsuario.add(jRadioButtonCliente);
        jRadioButtonCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonCliente.setSelected(true);
        jRadioButtonCliente.setText("Cliente");
        jRadioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClienteActionPerformed(evt);
            }
        });

        buttonGroupUsuario.add(jRadioButtonFuncionario);
        jRadioButtonFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonFuncionario.setText("Funcionário");
        jRadioButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoDeCadastroLayout = new javax.swing.GroupLayout(jPanelTipoDeCadastro);
        jPanelTipoDeCadastro.setLayout(jPanelTipoDeCadastroLayout);
        jPanelTipoDeCadastroLayout.setHorizontalGroup(
            jPanelTipoDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoDeCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTipoDeCadastroLayout.setVerticalGroup(
            jPanelTipoDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoDeCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCliente)
                    .addComponent(jRadioButtonFuncionario))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneUsuarios)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jPanelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTipoDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanelTipoDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBusca)
                    .addComponent(jButtonPesquisa)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonAtualizar))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClienteActionPerformed
        this.jLabelSenha.setVisible(false);
        this.jPasswordFieldSenha.setVisible(false);
        this.jLabelCargo.setVisible(false);
        this.jComboBoxCargo.setVisible(false);
        this.jPasswordFieldSenha.setText("");
        this.jComboBoxCargo.setSelectedIndex(0);
    }//GEN-LAST:event_jRadioButtonClienteActionPerformed

    private void jRadioButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncionarioActionPerformed
        this.jLabelSenha.setVisible(true);
        this.jPasswordFieldSenha.setVisible(true);
        this.jLabelCargo.setVisible(true);
        this.jComboBoxCargo.setVisible(true);
    }//GEN-LAST:event_jRadioButtonFuncionarioActionPerformed

    private void jFormattedTextFieldCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepKeyReleased
        String regexCEP = "\\d{5}-\\d{3}";
        if (this.jFormattedTextFieldCep.getText().matches(regexCEP)) {
            try {
                ViaCEP viaCep = new ViaCEP();
                viaCep.buscar(this.jFormattedTextFieldCep.getText());
                if (!viaCep.getLogradouro().isEmpty() && !viaCep.getBairro().isEmpty()) {
                    this.jTextFieldRua.setText(viaCep.getLogradouro());
                    this.jTextFieldBairro.setText(viaCep.getBairro());
                }
                this.jTextFieldEstado.setText(viaCep.getUf());
                this.jTextFieldCidade.setText(viaCep.getLocalidade());
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jFormattedTextFieldCepKeyReleased

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        switch (validaCampos()) {
            case 1:
                JOptionPane.showMessageDialog(null, "Valores não inseridos", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "E-mail inválido", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "CPF inválido", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "Data de nascimento inválida", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            default:
                String nome = this.jTextFieldNome.getText();
                String email = this.jTextFieldEmail.getText();
                String cpf = this.jFormattedTextFieldCpf.getText().replaceAll("[.\\-\\s]", "");
                String DtNasc = this.jFormattedTextFieldDataNascimento.getText();
                String senha = String.valueOf(this.jPasswordFieldSenha.getPassword());
                boolean nvAcess = (this.jComboBoxCargo.getSelectedItem().equals("Gerente") ? true : false);
                String cargo = this.jComboBoxCargo.getSelectedItem().equals("Gerente") ? "gerente" : "balconista";
                int cep = Integer.parseInt(this.jFormattedTextFieldCep.getText().replaceAll("[_-]", ""));
                String rua = this.jTextFieldRua.getText();
                int numero = Integer.parseInt(this.jTextFieldNumero.getText());
                String bairro = this.jTextFieldBairro.getText();
                String estado = this.jTextFieldEstado.getText();
                String cidade = this.jTextFieldCidade.getText();
                int idEndereco = 0;

                EnderecoModel endereco = new EnderecoModel(rua, numero, bairro, cep, cidade, estado);
                EnderecoController enderecoController = new EnderecoController();

                try {
                    idEndereco = enderecoController.createReturnId(endereco);
                    UsuarioModel usuario;

                    if (this.jRadioButtonCliente.isSelected()) {
                        usuario = new UsuarioModel(this.id, idEndereco, nome, email, cpf, DtNasc);
                    } else {
                        usuario = new UsuarioModel(this.id, idEndereco, nome, email, cpf, DtNasc, senha, nvAcess, cargo);
                    }
                    UsuarioController usuarioController = new UsuarioController();
                    usuarioController.create(usuario);

                    carregarUsuarios("");
                    limparCampos();
                } catch (KeyViolationException ex) {
                    Logger.getLogger(CadastroUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidKeyException ex) {
                    Logger.getLogger(CadastroUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        carregarUsuarios(this.jTextFieldBusca.getText().toLowerCase());
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        this.jButtonExcluir.setEnabled(true);
        this.jButtonAtualizar.setEnabled(true);
        this.jRadioButtonFuncionario.setEnabled(false);
        this.jRadioButtonCliente.setEnabled(false);
        this.jButtonCadastrar.setEnabled(false);
        this.jPasswordFieldSenha.setText("");

        this.id = Integer.parseInt((String) this.jTableUsuarios.getValueAt(getSelectedRow(), 0));
        Object valueNome = this.jTableUsuarios.getValueAt(getSelectedRow(), 1);
        Object valueEmail = this.jTableUsuarios.getValueAt(getSelectedRow(), 2);
        Object valueCpf = this.jTableUsuarios.getValueAt(getSelectedRow(), 3);
        Object valueDtNasc = this.jTableUsuarios.getValueAt(getSelectedRow(), 4);
        Object valueCargo = this.jTableUsuarios.getValueAt(getSelectedRow(), 5);
        Object valueRua = this.jTableUsuarios.getValueAt(getSelectedRow(), 6);
        Object valueNumero = this.jTableUsuarios.getValueAt(getSelectedRow(), 7);
        Object valueBairro = this.jTableUsuarios.getValueAt(getSelectedRow(), 8);
        Object valueCEP = this.jTableUsuarios.getValueAt(getSelectedRow(), 9);
        Object valueCidade = this.jTableUsuarios.getValueAt(getSelectedRow(), 10);
        Object valueEstado = this.jTableUsuarios.getValueAt(getSelectedRow(), 11);

        if (valueCargo == null) {
            this.jRadioButtonCliente.setSelected(true);
            this.jRadioButtonFuncionario.setEnabled(false);
            this.jRadioButtonCliente.setEnabled(false);
            this.jLabelSenha.setVisible(false);
            this.jPasswordFieldSenha.setVisible(false);
            this.jLabelCargo.setVisible(false);
            this.jComboBoxCargo.setVisible(false);
            this.jPasswordFieldSenha.setText("");
        } else {
            this.jRadioButtonFuncionario.setSelected(true);
            this.jRadioButtonFuncionario.setEnabled(false);
            this.jRadioButtonCliente.setEnabled(false);
            this.jLabelSenha.setVisible(true);
            this.jPasswordFieldSenha.setVisible(true);
            this.jLabelCargo.setVisible(true);
            this.jComboBoxCargo.setVisible(true);
        }

        this.jTextFieldNome.setText(String.valueOf(valueNome));
        this.jTextFieldEmail.setText(String.valueOf(valueEmail));
        this.jFormattedTextFieldCpf.setText(String.valueOf(valueCpf));
        this.jFormattedTextFieldDataNascimento.setText(DateFormatExample(String.valueOf(valueDtNasc)));
        this.jComboBoxCargo.setSelectedIndex("gerente".equals((String) valueCargo) ? 1 : 2);
        this.jFormattedTextFieldCep.setText(String.valueOf(valueCEP));
        this.jTextFieldRua.setText(String.valueOf(valueRua));
        this.jTextFieldNumero.setText(String.valueOf(valueNumero));
        this.jTextFieldBairro.setText(String.valueOf(valueBairro));
        this.jTextFieldEstado.setText(String.valueOf(valueEstado));
        this.jTextFieldCidade.setText(String.valueOf(valueCidade));
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        switch (validaCampos()) {
            case 1:
                JOptionPane.showMessageDialog(null, "Valores não inseridos", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "E-mail inválido", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "CPF inválido", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "Data de nascimento inválida", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            default:
                String nome = this.jTextFieldNome.getText();
                String email = this.jTextFieldEmail.getText();
                String cpf = this.jFormattedTextFieldCpf.getText().replaceAll("[.\\-\\s]", "");
                String DtNasc = this.jFormattedTextFieldDataNascimento.getText();
                String senha = String.valueOf(this.jPasswordFieldSenha.getPassword());
                boolean nvAcess = (this.jComboBoxCargo.getSelectedItem().equals("Gerente") ? true : false);
                String cargo = this.jComboBoxCargo.getSelectedItem().equals("Gerente") ? "gerente" : "balconista";
                int cep = Integer.parseInt(this.jFormattedTextFieldCep.getText().replaceAll("[_-]", ""));
                String rua = this.jTextFieldRua.getText();
                int numero = Integer.parseInt(this.jTextFieldNumero.getText());
                String bairro = this.jTextFieldBairro.getText();
                String estado = this.jTextFieldEstado.getText();
                String cidade = this.jTextFieldCidade.getText();
                int idEndereco = 0;

                EnderecoModel endereco = new EnderecoModel(this.id, rua, numero, bairro, cep, cidade, estado);
                EnderecoController enderecoController = new EnderecoController();

                try {
                    enderecoController.update(endereco);
                    UsuarioModel usuario;

                    if (this.jRadioButtonCliente.isSelected()) {
                        usuario = new UsuarioModel(this.id, idEndereco, nome, email, cpf, DtNasc);
                    } else {
                        usuario = new UsuarioModel(this.id, idEndereco, nome, email, cpf, DtNasc, senha, nvAcess, cargo);
                    }
                    UsuarioController usuarioController = new UsuarioController();
                    usuarioController.update(usuario);
                } catch (NotFoundException ex) {
                    Logger.getLogger(CadastroUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
                }

                carregarUsuarios("");
                limparCampos();
                this.jButtonCadastrar.setEnabled(true);
                this.jRadioButtonCliente.setEnabled(true);
                this.jRadioButtonFuncionario.setEnabled(true);
                this.jButtonExcluir.setEnabled(false);
                this.jButtonAtualizar.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        UsuarioController usuarioController = new UsuarioController();
        EnderecoController enderecoController = new EnderecoController();
        enderecoController.delete(usuarioController.deleteReturnId(this.id));

        carregarUsuarios("");
        limparCampos();
        this.jButtonCadastrar.setEnabled(true);
        this.jRadioButtonCliente.setEnabled(true);
        this.jRadioButtonFuncionario.setEnabled(true);
        this.jButtonExcluir.setEnabled(false);
        this.jButtonAtualizar.setEnabled(false);

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    public int validaCampos() {
        String nome = this.jTextFieldNome.getText();
        String email = this.jTextFieldEmail.getText();
        String cpf = this.jFormattedTextFieldCpf.getText().replaceAll("[.\\-\\s]", "");
        String nascimento = this.jFormattedTextFieldDataNascimento.getText();
        String cep = this.jFormattedTextFieldCep.getText().replaceAll("[_-]", "");
        String rua = this.jTextFieldRua.getText();
        String numero = this.jTextFieldNumero.getText();
        String bairro = this.jTextFieldBairro.getText();
        String estado = this.jTextFieldEstado.getText();
        String cidade = this.jTextFieldCidade.getText();

        String regex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);

        if (nome.isEmpty() || email.isEmpty() || cpf.length() < 11
                || nascimento.replaceAll("[_/-]", "").length() < 8 || cep.length() < 8
                || rua.isEmpty() || numero.isEmpty() || bairro.isEmpty()
                || estado.isEmpty() || cidade.isEmpty()) {
            return 1;
        } else if (this.jRadioButtonFuncionario.isSelected() && (this.jPasswordFieldSenha.getPassword().length == 0
                || String.valueOf(this.jComboBoxCargo.getSelectedItem()).isEmpty())) {
            return 1;
        } else if (!matcher.matches()) {
            return 2;
        } else if (!validarCPF(cpf)) {
            return 3;
        } else if (!validarDataNascimento(nascimento)) {
            return 4;
        }
        return 0;
    }

    public void carregarUsuarios(String busca) {
        if (!busca.isEmpty()) {

            UsuarioController usuarioController = new UsuarioController();
            ArrayList listaUsuario = usuarioController.readName(busca);

            this.jTableUsuarios.setModel(new UsuariosTableModel(listaUsuario));
        } else {
            UsuarioController usuarioController = new UsuarioController();
            ArrayList listaUsuario = usuarioController.readAllWithEndereco();

            this.jTableUsuarios.setModel(new UsuariosTableModel(listaUsuario));
        }
    }

    public void limparCampos() {
        this.id = 0;
        this.jRadioButtonCliente.setSelected(true);
        this.jTextFieldNome.setText("");
        this.jTextFieldEmail.setText("");
        this.jFormattedTextFieldCpf.setText("");
        this.jFormattedTextFieldDataNascimento.setText("");
        this.jLabelSenha.setVisible(false);
        this.jPasswordFieldSenha.setText("");
        this.jPasswordFieldSenha.setVisible(false);
        this.jLabelCargo.setVisible(false);
        this.jComboBoxCargo.setSelectedIndex(0);
        this.jComboBoxCargo.setVisible(false);
        this.jFormattedTextFieldCep.setText("");
        this.jTextFieldRua.setText("");
        this.jTextFieldNumero.setText("");
        this.jTextFieldBairro.setText("");
        this.jTextFieldEstado.setText("");
        this.jTextFieldCidade.setText("");
    }

    public int getSelectedRow() {
        return this.jTableUsuarios.getSelectedRow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupUsuario;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelTipoDeCadastro;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JRadioButton jRadioButtonCliente;
    private javax.swing.JRadioButton jRadioButtonFuncionario;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
