/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author augusto.zeni
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilmesJogos = new javax.swing.JMenu();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jMenuItemJogos = new javax.swing.JMenuItem();
        jMenuItemFilmes = new javax.swing.JMenuItem();
        jMenuPagamentos = new javax.swing.JMenu();
        jMenuItemTiposPagamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFilmesJogos.setText("Filmes/Jogos");

        jMenuItemGeneros.setText("Generos");
        jMenuItemGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosActionPerformed(evt);
            }
        });
        jMenuFilmesJogos.add(jMenuItemGeneros);

        jMenuItemJogos.setText("Jogos");
        jMenuFilmesJogos.add(jMenuItemJogos);

        jMenuItemFilmes.setText("Filmes");
        jMenuFilmesJogos.add(jMenuItemFilmes);

        jMenuBar1.add(jMenuFilmesJogos);

        jMenuPagamentos.setText("Pagamentos");

        jMenuItemTiposPagamentos.setText("Tipos de Pagamentos");
        jMenuItemTiposPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTiposPagamentosActionPerformed(evt);
            }
        });
        jMenuPagamentos.add(jMenuItemTiposPagamentos);

        jMenuBar1.add(jMenuPagamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosActionPerformed
        GeneroView generoView = new GeneroView();
        generoView.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosActionPerformed

    private void jMenuItemTiposPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTiposPagamentosActionPerformed
        TipoPagamentoView tipoPagamentoView = new TipoPagamentoView();
        tipoPagamentoView.setVisible(true);
    }//GEN-LAST:event_jMenuItemTiposPagamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilmesJogos;
    private javax.swing.JMenuItem jMenuItemFilmes;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemJogos;
    private javax.swing.JMenuItem jMenuItemTiposPagamentos;
    private javax.swing.JMenu jMenuPagamentos;
    // End of variables declaration//GEN-END:variables
}
