/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.TipoPagamentoController;
import Models.TipoPagamentoModel;
import TablesModel.TiposPagamentosTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author augusto.zeni
 */
public class TipoPagamentoView extends javax.swing.JFrame {

    /**
     * Creates new form TipoPagamentoView
     */
    public TipoPagamentoView() {
        initComponents();

        carregarTiposPagamentos();
        jButtonExcluir.setEnabled(false);
        jButtonAtualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTipoPagamento = new javax.swing.JTable();
        jButtonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FlicksNPlay - Cadastro De Pagamentos");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableTipoPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTipoPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTipoPagamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTipoPagamento);

        jButtonConfirmar.setText("Cadastrar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        String nome = this.jTextFieldNome.getText();

        if (validaCampos()) {
            JOptionPane.showMessageDialog(null, "Valores não inseridos", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            TipoPagamentoModel tipoPagamento = new TipoPagamentoModel(nome);

            TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
            tipoPagamentoController.create(tipoPagamento);
            carregarTiposPagamentos();
            limparCampos();
            jButtonExcluir.setEnabled(false);
            jButtonAtualizar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        Object valueId = this.jTableTipoPagamento.getValueAt(getSelectedRow(), 0);

        TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
        tipoPagamentoController.delete(Integer.parseInt((String) valueId));
        carregarTiposPagamentos();
        limparCampos();
        jButtonExcluir.setEnabled(false);
        jButtonAtualizar.setEnabled(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        String nome = this.jTextFieldNome.getText();
        Object id = Integer.parseInt((String) this.jTableTipoPagamento.getValueAt(getSelectedRow(), 0));

        if (validaCampos()) {
            JOptionPane.showMessageDialog(null, "Valores não inseridos", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            TipoPagamentoModel tipoPagamento = new TipoPagamentoModel((int) id, nome);

            TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
            tipoPagamentoController.update(tipoPagamento);
            carregarTiposPagamentos();
            limparCampos();
            jButtonExcluir.setEnabled(false);
            jButtonAtualizar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTableTipoPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTipoPagamentoMouseClicked
        jButtonExcluir.setEnabled(true);
        jButtonAtualizar.setEnabled(true);
        Object valueNome = this.jTableTipoPagamento.getValueAt(getSelectedRow(), 1);

        this.jTextFieldNome.setText((String) valueNome);
    }//GEN-LAST:event_jTableTipoPagamentoMouseClicked
    public void carregarTiposPagamentos() {
        TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
        ArrayList<TipoPagamentoModel> lista = tipoPagamentoController.readAll();
        this.jTableTipoPagamento.setModel(new TiposPagamentosTableModel(lista));
    }

    public void limparCampos() {
        this.jTextFieldNome.setText("");
    }

    public int getSelectedRow() {
        return this.jTableTipoPagamento.getSelectedRow();
    }

    public boolean validaCampos() {
        String nome = this.jTextFieldNome.getText();

        return nome.isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTipoPagamento;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
